### ISSUE TITLE
Kyverno CLI doesn't support variable substitution

### ISSUE THREAD

**Issue by corang** [defenseunicorns-labs/lula1#19]
As of now policies in the kyverno command line do not support variable substitution properly, especially around `apiUrl`. This is documented [here](https://github.com/kyverno/kyverno/issues/2777) and [here](https://github.com/kyverno/kyverno/issues/4513). Following is an example of a valid policy that does not work in the CLI due to variable substitution.
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: istio_AC-4
spec:
  rules:
  - name: istio-controlplane_AC-4(peer-auth-for-every-namespace)
    match:
      any:
      - resources:
          kinds:
          - "Pod"
    context:
    - name: peerAuthCount
      apiCall:
        urlPath: "apis/security.istio.io/v1beta1/namespaces/{{request.namespace}}/peerauthentications"
        jmesPath: "items | length(@)"
    validate:
      message: "Pods cannot be deployed without a PeerAuthentication"
      deny:
        conditions:
          any:
          - key: "{{peerAuthCount}}"
            operator: LessThan
            value: 1
```
