### ISSUE TITLE
Evidence mapping from OPA provider to Assessment-Results 

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#265]
Given the current implementation of Lula - we are no longer iterating over single resources to perform validation. Rather Lula wholistically collects all items to be assessed and performs validation of a payload of resources (1 -> n) using a Rego policy. 

This means that the current representation of items passing and failing do not serve a purpose. We should remove these from the reports.

Given Rego that establishes other key/value pairs in the [resultMap](https://github.com/defenseunicorns/lula/pull/263/files#diff-be4eb6e7e0cc9366b2eb4426ef1e44f26824b58ab104d9c8f33b775656f61092R173), we should:
- Require the `validate: bool` as a strict requirement and document it as such
- Allow for iterating over all other keys generically and mapping that data to a string that can be represented in an `observation` object in the `assessment-results` report. A generic map allows for the user to extend data available in the `resultMap` to include other evidence they might find valuable. Documenting how to accomplish this would be a great benefit to the OPA provider.

**Comment by meganwolf0** [comment]
I think maybe another option to strictly requiring `validate` as an output, would be to just have another field in the `payload` section maybe to indicate which bool field should be used to validate. So you could say like `validate.validate` (package.result) so ideally you could just grab whatever from the JSON result that comes out. It's like not the cleanest on the go side I don't think, but would provide the flexibility for people to add really whatever constructs they like and move toward decoupling the two more. 

Could possibly extend to the observations too? So a proposed structure in the yaml could be:
```
       payload:
          resources:
            - name: deployments
              resourceRule:
                Group: apps
                Version: v1
                Resource: deployments
                Namespaces: [istio-system]
          rego: |
            package validate
            validate := true
          output:
            validate: validate.validate
            observations:
            - validate.result.passed
            - validate.result.failed
```
