### ISSUE TITLE
Creation of draft releases

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#306]
Would like to consider the release process and the human element of surfacing what the delta of changes means to end users. 

By switching 
```
release:
  github:
    owner: defenseunicorns
    name: lula
  prerelease: auto
  mode: append
  draft: false
```

to 

```
release:
  github:
    owner: defenseunicorns
    name: lula
  prerelease: auto
  mode: append
  draft: true
```

go releaser will create a draft release - which enables the team to add more human elements to the release process.

Steps for release thereafter would incude:

- Create and push a tag from `main`
- Allow all pertinent checks to complete - including go release process
- Review the new `draft` release for a given tag
- Edit the draft release - Update or modify any pertinent information
- Publish the release 

Only then is the release marked as the `latest` release.
