### ISSUE TITLE
Refactor domain and resources

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#332]
The current validation structure has a somewhat confusing use of `domain` and `resources`, where they appear separate in the definition, but are coupled in practice - e.g.,
```yaml
target:
  provider: opa
  domain: kubernetes
  payload:
    resources:
      - {list of resources}
```

This flows into the code organization - e.g., getting the resources is implemented redundantly inside the provider modules.

The structure of both the validation yaml and implementation in code should probably be refactored to reduce redundant usage and enhance clarity.
