### ISSUE TITLE
Trim trailing whitespace in validations

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#483]
### Is your feature request related to a problem? Please describe.
If a validation has a rego structure, e.g.,
```yaml
...
provider:
  type: opa
  opa-spec:
    rego: |
      package validate
      ...
```
If any of the lines in the rego script have trailing whitespace the rego appears as one giant yaml string on compose, which is a little ugly. It would be nice for that to be trimmed or highlighted to the user in some way when linting.

### Describe the solution you'd like

- **Given** validation
- **When** trailing whitespace is trimmed
- **Then** compose composes beautifully

### Describe alternatives you've considered
None

### Additional context
None
