### ISSUE TITLE
Compose doesn't get all validations when links have comment blocks between them

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns-labs/lula1#484]
### Environment
Device and OS:  
App version:    
Kubernetes distro:  
Kubernetes version:  
provider:
- [ ] kyverno
- [ ] opa

### Steps to reproduce
1. Given an oscal file that has some comment text blocks between links:
```yaml
component-definition:
...
      implemented-requirements:
      - uuid: 9e158525-96bd-4d4f-a674-7e3eab9aea7a
        control-id: ac-4
        description: >-
          # Control Implementation
            Istio encrypts all in-mesh communication at runtime using FIPS verified mTLS in addition to ingress and egress gateways for controlling communication.
        remarks: >-
            # Control Description
            Information flow control regulates where information is allowed to travel within an information system and between information systems (as opposed to who is allowed to access the information) and without explicit regard to subsequent accesses to that information.
            Flow control restrictions include, for example, keeping export-controlled information from being transmitted in the clear to the Internet, blocking outside traffic that claims to be from within the organization, restricting web requests to the Internet that are not from the internal web proxy server, and limiting information transfers between organizations based on data structures and content.
        links:
          - href: 'file:../validations_library/istio/healthcheck/uds/validation.yaml'
            rel: lula
            text: Check that Istio is healthy
          # - href: 'file:../validations_library/istio/xxx/uds/validation.yaml'
          #  rel: lula
          #  text: Some comment here
          - href: 'file:../validations_library/istio/all-pods-istio-injected/uds/validation.yaml'
            rel: lula
            text: All pods are istio injected with proxyv2 sidecar
```
2. When running `lula t compose` on the file, it will not be able to pull in all validation links into backmatter

### Expected result
All validation links are pulled into backmatter

### Actual Result
Validations missing from backmatter

### Severity/Priority
Low 

### Additional Context
Wondering if simply running a `lula t upgrade` function prior to compose would solve this/be a reasonable fix? `upgrade` does automatically clear out those block comments.

**Comment by mildwonkey** [comment]
I ran through a couple of tests and this appears not to be an issue anymore  - @meganwolf0 can you help confirm? I want to make sure I'm not testing the wrong functionality.


I've been using this file in full, and both the OPA and kyverno validations show up after the compose: 

```yaml
component-definition:
  uuid: E6A291A4-2BC8-43A0-B4B2-FD67CAAE1F8F
  metadata:
    title: Lula Demo
    last-modified: "2022-09-13T12:00:00Z"
    version: "20220913"
    oscal-version: 1.1.2 # This version should remain one version behind latest version for `lula dev upgrade` demo
    parties:
      # Should be consistent across all of the packages, but where is ground truth?
      - uuid: C18F4A9F-A402-415B-8D13-B51739D689FF
        type: organization
        name: Lula Development
        links:
          - href: https://github.com/defenseunicorns/lula
            rel: website
  components:
    - uuid: A9D5204C-7E5B-4C43-BD49-34DF759B9F04
      type: software
      title: lula
      description: |
        Lula - the Compliance Validator
      purpose: Validate compliance controls
      responsible-roles:
        - role-id: provider
          party-uuids:
            - C18F4A9F-A402-415B-8D13-B51739D689FF # matches parties entry for Defense Unicorns
      control-implementations:
        - uuid: A584FEDC-8CEA-4B0C-9F07-85C2C4AE751A
          source: https://raw.githubusercontent.com/usnistgov/oscal-content/master/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json
          description: Validate generic security requirements
          implemented-requirements:
            - uuid: 42C2FFDC-5F05-44DF-A67F-EEC8660AEFFD
              control-id: ID-1
              description: >-
                This control validates that the demo-pod pod in the validation-test namespace contains the required pod label foo=bar in order to establish compliance.
              links:
                - href: "#a7377430-2328-4dc4-a9e2-b3f31dc1dff9"
                  rel: lula
                # remote opa validation
                - href: https://raw.githubusercontent.com/defenseunicorns/lula/main/src/test/e2e/scenarios/dev-validate/validation.yaml
                  rel: lula
                # remote opa validation
                # - href: https://raw.githubusercontent.com/defenseunicorns/lula/main/src/test/e2e/scenarios/dev-validate/validation.yaml
                #   rel: lula
                # remote kyverno validation
                - href: https://raw.githubusercontent.com/defenseunicorns/lula/main/src/test/e2e/scenarios/dev-validate/validation.kyverno.yaml
                  rel: lula
```

And here's the whole thing, composed:
```yaml
component-definition:
  back-matter:
    resources:
      - description: |
          domain:
            kubernetes-spec:
              create-resources: null
              resources:
              - description: ""
                name: podsvt
                resource-rule:
                  group: ""
                  name: ""
                  namespaces:
                  - validation-test
                  resource: pods
                  version: v1
            type: kubernetes
          lula-version: '>= v0.1.0'
          metadata:
            name: Kyverno validate pods with label foo=bar
            uuid: 2d9858bc-fb54-42e7-a928-43f840ac0ae6
          provider:
            kyverno-spec:
              policy:
                apiVersion: json.kyverno.io/v1alpha1
                kind: ValidatingPolicy
                metadata:
                  creationTimestamp: null
                  name: labels
                spec:
                  rules:
                  - assert:
                      all:
                      - check:
                          ~.podsvt:
                            metadata:
                              labels:
                                foo: bar
                    name: foo-label-exists
            type: kyverno
        title: Kyverno validate pods with label foo=bar
        uuid: 2d9858bc-fb54-42e7-a928-43f840ac0ae6
      - description: |
          domain:
            kubernetes-spec:
              create-resources: null
              resources:
              - description: ""
                name: podsvt
                resource-rule:
                  group: ""
                  name: ""
                  namespaces:
                  - validation-test
                  resource: pods
                  version: v1
              - description: ""
                name: empty
                resource-rule:
                  group: ""
                  name: ""
                  namespaces:
                  - doesnotexist
                  resource: pods
                  version: v1
            type: kubernetes
          lula-version: '>= v0.1.0'
          metadata:
            name: Validate pods with label foo=bar
            uuid: 7f4b12a9-3b8f-4a8e-9f6e-8c8f506c851e
          provider:
            opa-spec:
              rego: |
                package validate

                import future.keywords.every

                validate {
                  count(input.podsvt) > 0
                  count(input.empty) == 0
                  every pod in input.podsvt {
                    podLabel := pod.metadata.labels.foo
                    podLabel == "bar"
                  }
                }
            type: opa
        title: Validate pods with label foo=bar
        uuid: 7f4b12a9-3b8f-4a8e-9f6e-8c8f506c851e
  components:
    - control-implementations:
        - description: Validate generic security requirements
          implemented-requirements:
            - control-id: ID-1
              description: This control validates that the demo-pod pod in the validation-test namespace contains the required pod label foo=bar in order to establish compliance.
              links:
                - href: '#bce73bc6-8d5d-4d3e-8ec2-402431fe9b8e'
                  rel: lula
                - href: '#2d9858bc-fb54-42e7-a928-43f840ac0ae6'
                  rel: lula
                - href: '#c940f126-cc9e-4713-8c81-d35d396fa9c5'
                  rel: lula
                - href: '#aff793b3-6959-4951-9808-27d043e7a5af'
                  rel: lula
                - href: '#7f4b12a9-3b8f-4a8e-9f6e-8c8f506c851e'
                  rel: lula
              uuid: 42C2FFDC-5F05-44DF-A67F-EEC8660AEFFD
          source: https://raw.githubusercontent.com/usnistgov/oscal-content/master/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json
          uuid: A584FEDC-8CEA-4B0C-9F07-85C2C4AE751A
      description: |
        Lula - the Compliance Validator
      purpose: Validate compliance controls
      responsible-roles:
        - party-uuids:
            - C18F4A9F-A402-415B-8D13-B51739D689FF
          role-id: provider
      title: lula
      type: software
      uuid: A9D5204C-7E5B-4C43-BD49-34DF759B9F04
  metadata:
    last-modified: 2024-12-03T08:51:47.731818-05:00
    oscal-version: 1.1.2
    parties:
      - links:
          - href: https://github.com/defenseunicorns/lula
            rel: website
        name: Lula Development
        type: organization
        uuid: C18F4A9F-A402-415B-8D13-B51739D689FF
    title: Lula Demo
    version: "20220913"
  uuid: 59f67eab-e1a3-4523-be68-540c91e71b8d
```
