### ISSUE TITLE
yaml dependency investigation

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#56]
During initial proof-of-concept, we tangled together the use of 2-3 yaml library dependencies in order to read in kyverno cluster policy rules. 

"github.com/ghodss/yaml"
"sigs.k8s.io/yaml"

In efforts towards reducing dependency surface - would like to resolve the need of many if possible. 

Testing needs to ensure that all fields in a kyverno ClusterPolicy can be unmarshalled/marshalled

One test:
```
      - uuid: 6e1f05fc-3eab-45a2-9b16-d2c5acfed20b
        control-id: cm-7
        rules:
        - name: validate-nodeport
          match:
            any:
            - resources:
                kinds:
                - Service
          validate:
            message: "Services of type NodePort are not allowed."
            pattern:
              spec:
                =(type): "!NodePort"
```
