### ISSUE TITLE
generate annotation does not support > 1 control-implementations

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns-labs/lula1#572]
The generate annotation is a quick reference for how to reproduce a component generated with `lula generate component`.

This needs to be unique to a control-implementation instead of a component as a component can have 1 -> N control-implementations and each would require a unique generate command annotation

### Steps to reproduce
```bash
lula generate component -c https://raw.githubusercontent.com/usnistgov/oscal-content/master/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json -r ac-1,ac-3,ac-3.2,ac-4 -o oscal-component.yaml --remarks assessment-objective 
```

Review the annotation:
```yaml
remarks: |-
        This component was generated using the following command:
        	 lula generate component --catalog-source https://raw.githubusercontent.com/usnistgov/oscal-content/master/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json --component 'Component Title' --requirements ac-1,ac-3,ac-3.2,ac-4 --remarks assessment-objective
```

### Actual Result

Currently the above is the actual result - but the annotation is placed in `component[_].remarks` this would be overwritten if another control-implementation was generated in the same component,

### Expected Result

This annotation should be placed in a location that allows for 1 -> N annotations to exist for a given component.
