### ISSUE TITLE
Triage Label Action

### ISSUE THREAD

**Issue by CloudBeard** [defenseunicorns-labs/lula1#909]
### Describe what should be investigated or refactored

The Triage Label GitHub Action is pulling from main instead of a version.

### Links to any relevant code

[(optional) i.e. - <https://github.com/defenseunicorns/lula/blob/main/README.md?plain=1#L1>
](https://github.com/defenseunicorns/lula/blob/59a8a9d36267b6d0c2c12a672e5eff0983a68c90/.github/workflows/triage-label.yaml#L15)

### Additional context

We should switch to a version from main.

### Expected Deliverable

Change the digest from 

```yaml
name: Issue Triage Label

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Add triage label
      uses: actions/github-script@d70566966bbb446d06887700f68d905602745985
      with:
        script: |
          const issueNumber = context.issue.number;
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            labels: ['triage']
          });
```

to 
```yaml
name: Issue Triage Label

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Add triage label
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const issueNumber = context.issue.number;
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            labels: ['triage']
          });
```
